// Generated by CoffeeScript 1.4.0
(function() {
  var handle_swipe_right, init, open_login;

  init = function() {
    $('.jumbotron').fadeIn();
    return $(document).on('swipeRight', handle_swipe_right);
  };

  handle_swipe_right = function() {
    return $('.jumbotron').fadeOut(open_login);
  };

  open_login = function() {
    return window.location = 'login.html';
  };

  $(document).ready(init);

}).call(this);
