// Generated by CoffeeScript 1.4.0
(function() {
  var init, login_or_create_user, open_login;

  init = function() {
    return forge.prefs.get('user', login_or_create_user);
  };

  login_or_create_user = function(user) {
    var token;
    if (!user) {
      open_login();
    }
    token = user.facebook_access_token;
    return alert(token);
  };

  open_login = function() {
    return window.location = 'login.html';
  };

  $(document).ready(init);

}).call(this);
