// Generated by CoffeeScript 1.4.0
(function() {
  var handle_swipe_left, init, login, login_error, login_success, open_about;

  init = function() {
    $('.jumbotron').fadeIn();
    $(document).on('swipeLeft', handle_swipe_left);
    return $('.btn-primary').click(login);
  };

  handle_swipe_left = function() {
    return $('.jumbotron').fadeOut(open_about);
  };

  open_about = function() {
    return window.location = 'about.html';
  };

  login = function() {
    return forge.facebook.authorize(login_success, login_error);
  };

  login_success = function(token_information) {
    return alert(token_information);
  };

  login_error = function(error) {
    return alert(error);
  };

  $(document).ready(init);

}).call(this);
