// Generated by CoffeeScript 1.4.0
(function() {
  var init, login_or_create_login, open_login;

  init = function() {
    return forge.prefs.get('facebook_access_token', login_or_create_login);
  };

  login_or_create_login = function(token) {
    if (!token) {
      open_login();
      return;
    }
    // Login and get latest articles.
  };

  open_login = function() {
    return window.location = 'login.html';
  };

  $(document).ready(init);

}).call(this);
