// Generated by CoffeeScript 1.4.0
(function() {
  var get_items, init, login_or_create_login;

  init = function() {
    return forge.prefs.get('user_id', login_or_create_login);
  };

  login_or_create_login = function(user_id) {
    if (!user_id) {
      window.location = 'login.html';
      return;
    }
    return forge.facebook.hasAuthorized(get_items, function(error) {
      alert('Error signing in');
      return forge.facebook.logout(function() {
        return window.location = 'login.html';
      });
    });
  };

  get_items = function() {
    return alert('Getting articles');
  };

  $(document).ready(init);

}).call(this);
