// Generated by CoffeeScript 1.4.0
(function() {
  var get_latest, init, login_or_create_login, user_id;

  user_id = null;

  init = function() {
    return forge.prefs.get('user_id', login_or_create_login);
  };

  login_or_create_login = function(saved_user_id) {
    if (!saved_user_id) {
      window.location = 'login.html';
      return;
    }
    user_id = saved_user_id;
    return forge.facebook.hasAuthorized(get_latest, function(error) {
      alert('Error signing in');
      return forge.facebook.logout(function() {
        return window.location = 'login.html';
      });
    });
  };

  get_latest = function() {
    var get_latest_url, options;
    get_latest_url = 'http://connectedworld-dev.herokuapp.com/app/get/' + user_id + '/latest/';
    options = {
      url: get_latest_url,
      type: 'GET',
      dataType: 'json',
      success: function(response) {
        var article, box, image, row, title, _i, _len, _results;
        if (response.error) {
          alert('There was an error getting the latest articles.');
          return;
        }
        row = $('<div />').attr({
          "class": 'row'
        });
        $('.content').append(row);
        _results = [];
        for (_i = 0, _len = response.length; _i < _len; _i++) {
          article = response[_i];
          image = $('<img />').attr({
            "class": 'article_box_image',
            src: article.image_url
          });
          title = $('<div />').attr({
            "class": 'article_box_title'
          });
          title.text(article.title);
          box = $('<div />').attr({
            id: article.id.toString(),
            "class": 'article_box span2'
          });
          box.append(title);
          box.append(image);
          box.click(function(e) {
            return forge.prefs.set('next_article_id', this.id, function() {
              return window.location = 'article.html';
            });
          });
          _results.push(row.append(box));
        }
        return _results;
      }
    };
    return forge.request.ajax(options);
  };

  $(document).ready(init);

}).call(this);
