// Generated by CoffeeScript 1.4.0
(function() {
  var handle_swipe_left, init, logger, login, login_error, login_success, open_about, open_index, update_user;

  logger = forge.logging;

  init = function() {
    $('.jumbotron').fadeIn();
    $(document).on('swipeLeft', handle_swipe_left);
    return $('.btn-primary').click(login);
  };

  handle_swipe_left = function() {
    return $('.jumbotron').fadeOut(open_about);
  };

  open_about = function() {
    return window.location = 'about.html';
  };

  open_index = function() {
    return window.location = 'index.html';
  };

  login = function() {
    return forge.facebook.authorize(login_success, login_error);
  };

  login_success = function(token_information) {
    var access_token;
    access_token = token_information.access_token;
    return forge.prefs.set('facebook_access_token', access_token, open_index);
  };

  login_error = function(error) {
    return alert('Error: ' + error);
  };

  update_user = function(access_token) {};

  $(document).ready(init);

}).call(this);
